### ISSUE TITLE
one to one chat isn't working

### ISSUE THREAD

**Issue by nadeemkhan** [crabcanon/angularfire-ionic-chat#1]
Hi hope you doing well i just checked https://matsit.firebaseapp.com/ with two separate id group chat is working well but one to one isn't any idea?

**Comment by crabcanon** [comment]
Hey, did you mean you wanna send messages to yourself? Which tab did you refer to? Contacts or Groups?

**Comment by nadeemkhan** [comment]
Contacts, i tested with one of my friend but it's not working...

**Comment by nadeemkhan** [comment]
its working now thanks :-)
